### ISSUE TITLE
[FIXED] File name too long when saving SRT

### ISSUE THREAD

**Issue by benduckwdesign** [Xonshiz/Hulu-Subs-Downloader#2]
![screen shot 2016-07-12 at 5 16 53 pm](https://cloud.githubusercontent.com/assets/5730541/16783956/835ad41e-4854-11e6-95fb-3cb699b17225.png)

It's just a minor inconvenience-- it still outputs the link to download the .vtt, but I have a hunch that this isn't the intended behavior. A fix would be appreciated! I can provide additional information if necessary.

**Comment by Xonshiz** [comment]
From next time. please post the link to the video/show/movie along with it's name. I'll look into this one. The URL is : http://www.hulu.com/watch/530926 , correct?

And what are you using? The windows "EXE" version or the "Python" version?

Because on "Python" version, I cannot replicate the problem. It's downloading the srt without a file name though. which is also not the intended behaviour.

**Comment by Xonshiz** [comment]
Issue fixed and both the scripts have been updated. Let me know if the issue still persists, I'll open this issue again.
