### ISSUE TITLE
Japanese language support?

### ISSUE THREAD

**Issue by andthentheyran** [Xonshiz/Hulu-Subs-Downloader#26]
In the wiki it says 'feel free to open up an issue' for suggestions so that's what I'm doing here. Any chance support for Japanese subtitle downloading would be able to be added? I see it says that at the moment Hulu only offers English and Spanish, so maybe they're only available in Hulu Japan. Does that mean that it's impossible? 

Thanks!

**Comment by Xonshiz** [comment]
I've not seen Japanese subtitles on Hulu. Maybe some region thing? Could you share the links to videos where they have Japanese Subtitles so I can check that.

**Comment by andthentheyran** [comment]
The videos I am familiar with are all on the Japanese Hulu, so it's likely a region thing then. As an example there's https://www.hulu.jp/watch/60036232
Thank you for your rapid response!

**Comment by Xonshiz** [comment]
Cool thanks for the link. I'll check these out as soon as I get some time.

**Comment by Xonshiz** [comment]
I tried accessing hulu.jp and it seems like they're still following older layout? Also, I couldn't log in, it's catching my location and not even letting me log in, shows 403 right off the bat.
Also, I couldn't find any video on Hulu which had Japanese subtitles. If you come around any such video, please do post the link so I can add that support.

For now I'll close this because I couldn't find anything on "hulu.com" with Japanese subtitles.

feel free to re-open if you're able to find any such content.
