### ISSUE TITLE
[FIXED] Can't download any subtitles.

### ISSUE THREAD

**Issue by minkxlyons** [Xonshiz/Hulu-Subs-Downloader#3]
Hi, I've just downloaded latest version of [Hulu Subs Downloader Windows Binary](https://github.com/Xonshiz/Hulu-Subs-Downloader/blob/master/Hulu%20Subs%20Downloader%20-%20Windows%20Binary.rar.rar?raw=true) and I also have followed [your Youtube tutorial](https://www.youtube.com/watch?v=Ymrh99SUpUQ&feature=youtu.be) but I can't download anything. I have tried this [link](http://www.hulu.com/watch/249959) for single video and this [link](http://www.hulu.com/rupauls-drag-race) for whole series. After running program, the screen shows up the text "Writing Links to the File..." and there was no subtitles downloaded. But there was a new file created by the program and It was named "newfile.txt" in the same folder with the  program. I have uploaded this file to [pastebin](http://pastebin.com/3K2FGPGf). Please, fix this soon!

**Comment by Xonshiz** [comment]
Hey,
Ah, thanks for notifying. I have updated the whole repository to fix the issue and reflect the changes. However, note that the "Batch Subs Downloading" won't work, because Hulu won't let logged out users to access the "Links" to single episodes. This caused the batch subs ripper to be shut down.
This will definitely take a shit load amount of time to fix. I'll have to figure out a workaround for this.
